apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acme-challenge-test
  creationTimeStamp: null
spec:
  rules:
  - host: your.domain.com
    http:
      paths:
      - backend:
          serviceName: acme-challenge-test
          servicePort: 5000
        path: /.well-known/acme-challenge/asdf1234
        pathType: ImplementationSpecific
status: {}
