name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: tag
      run: echo "::set-output name=TAG::$(date +%s)"
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag regionorebrolan/acme-challenge-test:${{ steps.tag.outputs.TAG }}
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKE_USERNAME }}
        password: ${{ secrets.DOCKER_BUILD_TOKEN }}
    - name: docker push
      run: docker push regionorebrolan/acme-challenge-test:$TAG
